name: Build_n_Test
run-name: Deploy by @ ${{github.actor}} by event ${{github.event_name}}
on: 
  workflow_dispatch:
concurrency:
  group: ${{github.actor_id}}-${{github.workflow}}
  cancel-in-progress: true
jobs:
  Test: 
    uses: ./.github/workflows/test.yml
    with:
      path: ./AsyncMessage.Test/AsyncMessage.test.csproj
  
       


        
                


