name: .Net
run-name: Deploy by @ ${{github.actor}} by event ${{github.event_name}}
on: 
    workflow_dispatch:
    schedule:
      - cron: '00 00 * * 1-5'
jobs:
  Test: 
    runs-on: ubuntu-latests
    steps:
    - name: Unit_Test
      uses: ./test
      with:
        path: ./AsyncMessage.Test/AsyncMessage.test.csproj
  
       


        
                


